[package]
name = "trax-lsp-server"
version = "0.1.0"
edition = "2021"

[dependencies]
lsp-server = "0.7"
lsp-types = "0.95"
serde = "1.0.197"
serde_json = "1.0.114"
trax-parser = { path = "../../lib/parser" }
